### ISSUE TITLE
facefinder.cpp:100: += on uninit data ?

### ISSUE THREAD

**Issue by dcb314** [enGits/engrid#50]
facefinder.cpp:100:7: warning: variable 'ave_num_faces' is uninitialized when used here [-Wuninitialized]

      ave_num_faces += double(m_Faces[cell].size());

Suggest init local variable ave_num_faces to zero before first use.

**Comment by ftpronk** [comment]
Pushed. Thank you for your post.

Be aware that the latest release of engrid is still in a semi experimental state.  A cleaned-out version should be release soon.  (Workload allowing..)
