### ISSUE TITLE
no-return-in-nonvoid-function

### ISSUE THREAD

**Issue by awissu** [enGits/engrid#51]
Hello!
I can not build a package in OBS.
OBS has a RPMLINT check and its output gave me the following errors:

[  935s] E: engrid no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/engrid-2.0.0git.20150324/src/build/libengrid/../../libengrid/cadinterface.h:125, 126
[  935s] E: engrid no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/engrid-2.0.0git.20150324/src/build/libengrid/../../libengrid/edgelengthsource.h:43
[  935s] E: engrid no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/engrid-2.0.0git.20150324/src/libengrid/cadinterface.h:125, 126
[  935s] E: engrid no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/engrid-2.0.0git.20150324/src/libengrid/cgaltricadinterface.cpp:292, 297
[  935s] E: engrid no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/engrid-2.0.0git.20150324/src/libengrid/edgelengthsource.h:43

Thank you for the attention, hope this report helps development.

**Comment by ftpronk** [comment]
Sorry for the delay.
Normally, the code should have compiled without issues, even though it is formally wrong to have no return on a none-void function..  Does Rpmlint enforce stricter rules than gcc?

Anyhow, I pushed a solution to this issue, so give it an other try when you have time.

Kind regards.
