### ISSUE TITLE
Wiki images upload

### ISSUE THREAD

**Issue by emerrf** [enGits/engrid#56]
Hi,
After following the tutorial enGrid 1.3 ([Complete Mesh for a Damper in a duct](https://github.com/enGits/engrid/wiki/Complete-Mesh-for-a-damper-in-a-duct-%28starting-from-an-STL-geometry%29)), I wanted to contribute some of my notes once I successfully managed to load the case into paraFoam. I decided to update the wiki page but I couldn't upload some of the screenshots which I am attaching here. The files should be placed in the `images` directory inside the `engrid.wiki` repo. That's all.

Congratulations for the great work and thank you very much for sharing it with the community!
Emer

![damper_bc_types](https://cloud.githubusercontent.com/assets/10027328/12706183/2c1ca9d2-c877-11e5-94e6-eeeb65377d70.png)
![damper_map_bc_types](https://cloud.githubusercontent.com/assets/10027328/12706182/2c00fb06-c877-11e5-84b5-7d345d69efaf.png)
![damper_explore_mesh_parafoam](https://cloud.githubusercontent.com/assets/10027328/12706184/2c2763a4-c877-11e5-8abd-a09efbc0291c.png)

**Comment by ftpronk** [comment]
Thank you for the update, and enjoy using enGrid!

Kind regards,
F.
